plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

minecraft {
    // 使用官方映射，版本号从 gradle.properties 读取
    mappings channel: 'official', version: minecraft_version

    // 启用 Access Transformer
    accessTransformers {
        file('src/main/resources/META-INF/accesstransformer.cfg')
    }
}

dependencies {
    // NeoForge 核心依赖
    implementation "net.neoforged:neoforge:${neo_version}"
}
